import { Hono } from 'hono';
import { healthRouter } from './health.js';
import { authRouter } from './auth.js';
import { devLoginRouter } from './dev-login.js';
import { emailRouter } from './email.js';
import { phoneRouter } from './phone.js';
import { categoryRouter } from './categories.js';
import { provinceRouter } from './provinces.js';
import { listingRouter } from './listings.js';
import { searchRouter } from './search.js';
import { uploadRouter } from './uploads.js';
import { conversationRouter } from './conversations.js';
import { favoriteRouter } from './favorites.js';
import { articleRouter } from './articles.js';
import { tenderRouter } from './tenders.js';
import { paymentRouter } from './payments.js';
import { walletRouter } from './wallet.js';
import { accountRouter, dealerDashboardRouter, dealerPublicRouter } from './dealers.js';
import { userRouter } from './users.js';
import { adminRouter } from './admin.js';
import { notificationRouter } from './notifications.js';
import { meRouter } from './me.js';
import { partsRouter } from './parts.js';
import { storeRouter } from './store.js';
import { escrowRouter } from './escrow.js';
import { statsRouter } from './stats.js';
import { listingV2Router } from './v2-listings.js';
import { userV2Router } from './v2-users.js';
import { vehicleV2Router } from './v2-vehicles.js';
import { taxonomyV2Router } from './v2-taxonomies.js';
import { paymentV2Router } from './v2-payments.js';
import { tenderV2Router } from './v2-tenders.js';
import { provinceV2Router } from './v2-provinces.js';
import { categoryV2Router } from './v2-categories.js';
import { attributeV2Router } from './v2-attributes.js';
import { articleV2Router } from './v2-articles.js';
import { favoriteV2Router } from './v2-favorites.js';
import { notificationV2Router } from './v2-notifications.js';
import { emailV2Router } from './v2-email.js';
import { phoneV2Router } from './v2-phone.js';
import { dealerV2Router } from './v2-dealers.js';
import { authV2Router } from './v2-auth.js';
import { meV2Router } from './v2-me.js';
import { healthV2Router } from './v2-health.js';
import { conversationV2Router } from './v2-conversations.js';
import { uploadV2Router } from './v2-uploads.js';
import { partsV2Router } from './v2-parts.js';
import { contentV2Router } from './v2-contents.js';
import { v2CatalogsRoutes } from './v2-catalogs.js';
import { workshopV2Router } from './v2-workshops.js';

const router = new Hono();

router.get('/', (c) => c.json({ success: true, data: { name: 'Marketplace API', version: '1.0.0', docs: '/api/v1/docs' } }));
router.get('/v2', (c) => c.json({ success: true, data: { version: '2.0.0', endpoints: ['parts', 'listings', 'users', 'vehicles', 'categories', 'dealers', 'payments', 'tenders', 'articles', 'favorites', 'notifications', 'conversations', 'auth', 'me', 'health', 'upload', 'contents'] } }));

router.route('/health', healthRouter);
router.route('/auth', authRouter);
router.route('/dev', devLoginRouter);
router.route('/email', emailRouter);
router.route('/phone', phoneRouter);
router.route('/categories', categoryRouter);
router.route('/provinces', provinceRouter);
router.route('/listings', listingRouter);
router.route('/search', searchRouter);
router.route('/upload', uploadRouter);
router.route('/conversations', conversationRouter);
router.route('/favorites', favoriteRouter);
router.route('/articles', articleRouter);
router.route('/tenders', tenderRouter);
router.route('/payments', paymentRouter);
router.route('/wallet', walletRouter);
router.route('/account', accountRouter);
router.route('/dealer', dealerDashboardRouter);
router.route('/dealers', dealerPublicRouter);
router.route('/users', userRouter);
router.route('/admin', adminRouter);
router.route('/notifications', notificationRouter);
router.route('/me', meRouter);
router.route('/parts', partsRouter);
router.route('/store', storeRouter);
router.route('/escrow', escrowRouter);
router.route('/stats', statsRouter);
router.route('/v2/listings', listingV2Router);
router.route('/v2/users', userV2Router);
router.route('/v2/vehicles', vehicleV2Router);
router.route('/v2/taxonomies', taxonomyV2Router);
router.route('/v2/payments', paymentV2Router);
router.route('/v2/tenders', tenderV2Router);
router.route('/v2/provinces', provinceV2Router);
router.route('/v2/categories', categoryV2Router);
router.route('/v2/attributes', attributeV2Router);
router.route('/v2/articles', articleV2Router);
router.route('/v2/favorites', favoriteV2Router);
router.route('/v2/notifications', notificationV2Router);
router.route('/v2/email', emailV2Router);
router.route('/v2/phone', phoneV2Router);
router.route('/v2/dealers', dealerV2Router);
router.route('/v2/auth', authV2Router);
router.route('/v2/me', meV2Router);
router.route('/v2/health', healthV2Router);
router.route('/v2/conversations', conversationV2Router);
router.route('/v2/upload', uploadV2Router);
router.route('/v2/parts', partsV2Router);
router.route('/v2/contents', contentV2Router);
router.route('/v2/catalogs', v2CatalogsRoutes);
router.route('/v2/workshops', workshopV2Router);

export { router as apiRouter };
