import { Hono } from 'hono';
import { healthRouter } from './health.js';
import { authRouter } from './auth.js';
import { emailRouter } from './email.js';
import { phoneRouter } from './phone.js';
import { categoryRouter } from './categories.js';
import { provinceRouter } from './provinces.js';
import { listingRouter } from './listings.js';
import { searchRouter } from './search.js';
import { uploadRouter } from './uploads.js';
import { conversationRouter } from './conversations.js';
import { favoriteRouter } from './favorites.js';
import { articleRouter } from './articles.js';
import { tenderRouter } from './tenders.js';
import { paymentRouter } from './payments.js';
import { walletRouter } from './wallet.js';
import { accountRouter, dealerDashboardRouter, dealerPublicRouter } from './dealers.js';
import { userRouter } from './users.js';
import { adminRouter } from './admin.js';
import { notificationRouter } from './notifications.js';
import { meRouter } from './me.js';
import { partsRouter } from './parts.js';
import { escrowRouter } from './escrow.js';

const router = new Hono();

router.route('/health', healthRouter);
router.route('/auth', authRouter);
router.route('/email', emailRouter);
router.route('/phone', phoneRouter);
router.route('/categories', categoryRouter);
router.route('/provinces', provinceRouter);
router.route('/listings', listingRouter);
router.route('/search', searchRouter);
router.route('/upload', uploadRouter);
router.route('/conversations', conversationRouter);
router.route('/favorites', favoriteRouter);
router.route('/articles', articleRouter);
router.route('/tenders', tenderRouter);
router.route('/payments', paymentRouter);
router.route('/wallet', walletRouter);
router.route('/account', accountRouter);
router.route('/dealer', dealerDashboardRouter);
router.route('/dealers', dealerPublicRouter);
router.route('/users', userRouter);
router.route('/admin', adminRouter);
router.route('/notifications', notificationRouter);
router.route('/me', meRouter);
router.route('/parts', partsRouter);
router.route('/escrow', escrowRouter);

export { router as apiRouter };
